import { FaReact } from "react-icons/fa";

export const ExperiencesTabs = [
  { id: "tab-1", label: "Work", title: "Work Experience" },
  { id: "tab-2", label: "Education", title: "Education" },
  { id: "tab-3", label: "Upskill", title: "Upskill Certificates" },
];

export const ExperiencesDataWork = [
  {
    id: "work-1",
    icon: <FaReact className="scale-150" />,
    iconStyle: { background: "#1E293B", color: "#61DAFB" },
    title: "Frontend Wordpress Developer",
    company: "Freelance",
    date: "July 2025 - Present",
    tags: ["React", "JavaScript", "CSS", "HTML"],
    bullets: [
      "Built and delivered custom web solutions for small businesses, optimizing their online presence.",
      "Worked on multiple freelance projects while managing academic responsibilities effectively.",
      // "Enhanced client websites with responsive designs and modern UI/UX practices.",
      // "Developed interactive components using React to streamline user experiences.",
      // "Collaborated with clients to gather requirements and deliver tailored solutions under tight deadlines.",
      // "Gained proficiency in time management and prioritization through balancing academic and work commitments.",
    ],
  },
  {
    id: "work-2",
    icon: <FaReact className="scale-150" />,
    iconStyle: { background: "#1E293B", color: "#61DAFB" },
    title: "Fullstack Web Developer Intern",
    company: "Accenture",
    date: "February 2023 - May 2025",
    tags: ["React", "JavaScript", "CSS", "HTML"],
    bullets: [
      "Acquired comprehensive  expertise of Java and web development through online courses on Udemy.",
      "Designed and implemented dynamic user interfaces using HTML, CSS, and JavaScript, ensuring responsive and user-friendly designs.",
      "Enhanced database management skills by implementing relational database models for java and web applications.",
      "Integrated data structures with frontend components.",
      "Managed and logged work hours using Jibble, demonstrating effective time management and remote work discipline.",
    ],
  },
  {
    id: "work-3",
    icon: <FaReact className="scale-150" />,
    iconStyle: { background: "#1E293B", color: "#61DAFB" },
    title: "Working Student",
    company: "Freelance",
    date: "January 2023 - January 2025",
    tags: ["HTML", "CSS", "JavaScript"],
    bullets: [
      "Acquired comprehensive  expertise of Java and web development through online courses on Udemy.",
      "Designed and implemented dynamic user interfaces using HTML, CSS, and JavaScript, ensuring responsive and user-friendly designs.",
      "Enhanced database management skills by implementing relational database models for java and web applications.",
      "Integrated data structures with frontend components.",
      "Managed and logged work hours using Jibble, demonstrating effective time management and remote work discipline.",
    ],
  },
];

export const ExperiencesDataEducation = [
  {
    id: "edu-1",
    degree: "Bachelor of Computer Science",
    institution: "STI College Sta. Mesa",
    graduationDate: "July 2025",
    description: "Sta. Mesa, Manila, Metro Manila",
  },
];

export const ExperiencesDataUpskill = [
  {
    id: "ups-1",
    title: "The Ultimate React Course 2025 React, Next.js, Redux & More",
    platform: "Udemy",
    date: "April 2025",
    tags: [
      "React.js",
      "Components",
      "Props",
      "Keys",
      "State Mangement",
      "Server Side and Client Side Rendering",
      "Hooks",
      "Routing",
      "Context API",
      "Advanced State Mangement",
      "Redux",
      "SupaBase",
      "Middleware",
      "JavaScript",
      "EJS",
      "JQuery",
      "Express.js",
      "Node.js",
      "React",
      "PostgreSQL",
    ],
  },
  {
    id: "ups-2",
    title: "The Complete Full-Stack Web Development Bootcamp",
    platform: "Udemy",
    date: "April 2025",
    tags: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "Web Design",
      "Document Object Model (DOM)",
      "JavaScript ES6",
      "React.js",
      "Unix/Linux Terminal",
      "Git",
      "GitHub",
      "Version Control",
      "Express.js",
      "Node.js",
      "Application Program Interfaces (API)",
      "EJS",
      "JQuery",
      "Database Fundamental",
      "SQL",
      "PostgreSQL",
      "Deployment",
      "RESTful APIs",
      "Authentication & Security",
      "Web3 Basics",
      "Blockchain",
      "Crypto",
      "NFT & Marketplace",
      "Markdown",
    ],
  },
  {
    id: "ups-3",
    title: "Tech Writers Master Class",
    platform: "Udemy",
    date: "April 2025",
    tags: ["Technical Writing", "Technical Documentation", "Markdown"],
  },
  {
    id: "ups-4",
    title: "Git Complete The definitive, step-by-step guide to Git",
    platform: "Udemy",
    date: "March 2025",
    tags: ["Git", "GitHub", "GitHub Desktop", "Version Control"],
  },
  {
    id: "ups-5",
    title: "Learn Visual Studio Code",
    platform: "Udemy",
    date: "March 2025",
    tags: ["Visual Studio Code"],
  },
];
