// Sample: For easy copy
// {
//   title: "Lorem Ipsum Project",
//   subtitle: "Lorem Ipsum Subtitle",
//   thumbnail: "/thumbnails/lorem-ipsum-desktop.png",
//   alt: "Screenshot of Lorem Ipsum Project on desktop",
//   tags: [{ id: 0, tag: "Lorem" }, { id: 1, tag: "Ipsum" }],
//   linkRepository: "https://github.com/example/lorem-ipsum",
//   linkLiveDemo: "https://lorem-ipsum-demo.com",
//   linkCaseStudy: "https://lorem-ipsum-case-study.com",
// },

export const ProjectsDataFeatured = [
  {
    title: "Roadway Delivery",
    thumbnail: "/thumbnails/RWD_Thumbnail.jpg",
    alt: "RWD full landing page on desktop with logo",
    tags: ["Next.js", "Typescript", "Tailwind", "CSS", "HTML"],
    description: "A landing page for a delivery service.",
    linkRepository: "https://github.com/ierdss/road-way-delivery",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "",
  },
  {
    title: "Commemoration Gallery",
    thumbnail: "/thumbnails/remembrance-gallery.png",
    alt: "Commemoration Gallery full page on desktop",
    tags: ["next.js", "cloudinary", "typescript", "tailwind"],
    description: "An image gallery to commemorate my loved ones.",
    linkRepository: "https://github.com/ierdss/family-friends_image-gallery",
    linkLiveDemo: "https://remembrance-gallery.vercel.app",
    linkCaseStudy: "",
  },
];

export const ProjectsDataAll = [
  {
    id: 1,
    title: "Roadway Delivery",
    subtitle: "Delivery Service (Landing Page)",
    desktopThumbnail: "/thumbnails/RWD_Thumbnail.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: ["Next.js", "Typescript", "Tailwind", "CSS", "HTML"],
    description: "Hello World!",
    linkRepository: "https://github.com/AndreiSager/road-way-delivery",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "",
  },
  {
    id: 2,
    title: "Commemoration Gallery",
    subtitle: "Image Gallery",
    desktopThumbnail: "/thumbnails/remembrance-gallery.png",
    desktopAlt: "",
    mobileThumbnail: "",
    mobileAlt: "",
    platformDesktop: true,
    platformMobile: true,
    tags: ["next.js", "cloudinary", "typescript", "tailwind"],
    description: "Hello World!",
    linkRepository:
      "https://github.com/AndreiSager/family-friends_image-gallery",
    linkLiveDemo: "https://remembrance-gallery.vercel.app",
    linkCaseStudy: "",
  },
  {
    id: 3,
    title: "Roadway Delivery",
    subtitle: "Delivery Service (Landing Page)",
    desktopThumbnail: "/thumbnails/road-way-delivery.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: ["Next.js", "Typescript", "Tailwind", "CSS", "HTML"],
    description: "Hello World!",
    linkRepository: "https://github.com/AndreiSager/road-way-delivery",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "",
  },
  {
    id: 4,
    title: "Commemoration Gallery",
    subtitle: "Image Gallery",
    desktopThumbnail: "/thumbnails/remembrance-gallery.png",
    desktopAlt: "",
    mobileThumbnail: "",
    mobileAlt: "",
    platformDesktop: true,
    platformMobile: true,
    tags: ["next.js", "cloudinary", "typescript", "tailwind"],
    description: "Hello World!",
    linkRepository:
      "https://github.com/AndreiSager/family-friends_image-gallery",
    linkLiveDemo: "https://remembrance-gallery.vercel.app",
    linkCaseStudy: "",
  },
];

// {
//   id: 0,
//   title: "Lorebuilder",
//   subtitle: "World Building",
//   desktopThumbnail: "",
//   desktopAlt: "Lorebuilder On Desktop",
//   mobileThumbnail: "",
//   mobileAlt: "Lorebuilder On Mobile",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [{ id: 1, tag: "Electron.js" }],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },
// {
//   id: 1,
//   title: "Samura",
//   subtitle: "e-commerce shop",
//   desktopThumbnail: "",
//   desktopAlt: "Samura On Desktop",
//   mobileThumbnail: "",
//   mobileAlt: "Samura On Mobile",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [
//     { id: 1, tag: "Next.js" },
//     { id: 2, tag: "Typescript" },
//     { id: 3, tag: "Tailwind" },
//     { id: 4, tag: "CSS" },
//   ],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },
// {
//   id: 2,
//   title: "Bridge",
//   subtitle: "Social Platform",
//   desktopThumbnail: "/projects-thumbnails/bridge__compressed-desktop.jpg",
//   desktopAlt: "RWD full page on desktop",
//   mobileThumbnail: "/projects-thumbnails/bridge__compressed-mobile.jpg",
//   mobileAlt: "RWD full page on mobile",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [
//     { id: 1, tag: "Next.js" },
//     { id: 2, tag: "Typescript" },
//     { id: 3, tag: "Tailwind" },
//     { id: 4, tag: "CSS" },
//   ],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },
// {
//   id: 3,
//   title: "Roadway Delivery (App)",
//   subtitle: "Social Platform",
//   desktopThumbnail: "",
//   desktopAlt: "RWD full page on desktop",
//   mobileThumbnail: "",
//   mobileAlt: "RWD full page on mobile",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [
//     { id: 1, tag: "Next.js" },
//     { id: 2, tag: "Typescript" },
//     { id: 3, tag: "Tailwind" },
//     { id: 4, tag: "CSS" },
//   ],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },

// {
//   id: 0,
//   title: "Marked A.I.",
//   subtitle: "Artificial Intelligence",
//   desktopThumbnail:
//     "/projects-thumbnails/road-way-delivery__compressed-desktop.jpg",
//   desktopAlt: "RWD full page on desktop",
//   mobileThumbnail: "/projects-thumbnails/road-way-delivery__compressed-mobile.jpg",
//   mobileAlt: "RWD full page on mobile",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [
//     { id: 1, tag: "Next.js" },
//     { id: 2, tag: "Typescript" },
//     { id: 3, tag: "Tailwind" },
//     { id: 4, tag: "CSS" },
//   ],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },
// {
//   id: 1,
//   title: "Shoutcaster",
//   subtitle: "Video Sharing",
//   desktopThumbnail:
//     "/projects-thumbnails/road-way-delivery__compressed-desktop.jpg",
//   desktopAlt: "RWD full page on desktop",
//   mobileThumbnail: "/projects-thumbnails/road-way-delivery__compressed-mobile.jpg",
//   mobileAlt: "RWD full page on mobile",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [
//     { id: 1, tag: "Next.js" },
//     { id: 2, tag: "Typescript" },
//     { id: 3, tag: "Tailwind" },
//     { id: 4, tag: "CSS" },
//   ],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },
// {
//   id: 2,
//   title: "Roadway Delivery (Landing Page)",
//   subtitle: "Transport Service",
//   desktopThumbnail:
//     "/projects-thumbnails/road-way-delivery__compressed-desktop.jpg",
//   desktopAlt: "RWD full page on desktop",
//   mobileThumbnail: "/projects-thumbnails/road-way-delivery__compressed-mobile.jpg",
//   mobileAlt: "RWD full page on mobile",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [
//     { id: 1, tag: "Next.js" },
//     { id: 2, tag: "Typescript" },
//     { id: 3, tag: "Headless UI" },
//     { id: 4, tag: "Next Auth" },
//     { id: 5, tag: "Emailjs" },
//     { id: 6, tag: "Tailwind" },
//     { id: 7, tag: "CSS" },
//     { id: 8, tag: "Sass" },
//   ],
//   linkRepository: "https://github.com/LordBrim/andrei-portfolio",
//   linkLiveDemo: "https://roadwaydelivery.vercel.app",
//   linkCaseStudy: "/",
// },
