import { v4 as uuidv4 } from "uuid";

export const ProjectsDataFeatured = [
  {
    id: uuidv4(),
    title: "Roadway Delivery",
    thumbnail: "/thumbnails/RWD_Thumbnail.jpg",
    alt: "RWD full landing page on desktop with logo",
    tags: [
      { id: uuidv4(), text: "Next.js" },
      { id: uuidv4(), text: "Typescript" },
      { id: uuidv4(), text: "Tailwind" },
      { id: uuidv4(), text: "CSS" },
      { id: uuidv4(), text: "HTML" },
      { id: uuidv4(), text: "Figma" },
    ],
    description: "A landing page for a delivery service mobile app.",
    linkRepository: "https://github.com/ierdss/road-way-delivery",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "",
  },
  {
    id: uuidv4(),
    title: "Commemoration Gallery",
    thumbnail: "/thumbnails/remembrance-gallery.png",
    alt: "Commemoration Gallery full page on desktop",
    tags: [
      { id: uuidv4(), text: "Next.js Template" },
      { id: uuidv4(), text: "Cloudinary API" },
      { id: uuidv4(), text: "TypeScript" },
      { id: uuidv4(), text: "Tailwind" },
    ],
    description: "An image gallery to commemorate my loved ones.",
    linkRepository: "https://github.com/ierdss/family-friends_image-gallery",
    linkLiveDemo: "https://remembrance-gallery.vercel.app",
    linkCaseStudy: "",
  },
];

export const ProjectsDataAll = [
  {
    id: uuidv4(),
    title: "Roadway Delivery",
    subtitle: "Delivery Service (Landing Page)",
    desktopThumbnail: "/thumbnails/RWD_Thumbnail.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: uuidv4(), text: "Next.js" },
      { id: uuidv4(), text: "Typescript" },
      { id: uuidv4(), text: "Tailwind" },
      { id: uuidv4(), text: "CSS" },
      { id: uuidv4(), text: "HTML" },
    ],
    description: "Hello World!",
    linkRepository: "https://github.com/AndreiSager/road-way-delivery",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "",
  },
  {
    id: uuidv4(),
    title: "Commemoration Gallery",
    subtitle: "Image Gallery",
    desktopThumbnail: "/thumbnails/remembrance-gallery.png",
    desktopAlt: "",
    mobileThumbnail: "",
    mobileAlt: "",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: uuidv4(), text: "next.js" },
      { id: uuidv4(), text: "cloudinary" },
      { id: uuidv4(), text: "typescript" },
      { id: uuidv4(), text: "tailwind" },
    ],
    description: "Hello World!",
    linkRepository:
      "https://github.com/AndreiSager/family-friends_image-gallery",
    linkLiveDemo: "https://remembrance-gallery.vercel.app",
    linkCaseStudy: "",
  },
  {
    id: uuidv4(),
    title: "Roadway Delivery",
    subtitle: "Delivery Service (Landing Page)",
    desktopThumbnail: "/thumbnails/road-way-delivery.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: uuidv4(), text: "Next.js" },
      { id: uuidv4(), text: "Typescript" },
      { id: uuidv4(), text: "Tailwind" },
      { id: uuidv4(), text: "CSS" },
      { id: uuidv4(), text: "HTML" },
    ],
    description: "Hello World!",
    linkRepository: "https://github.com/AndreiSager/road-way-delivery",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "",
  },
  {
    id: uuidv4(),
    title: "Commemoration Gallery",
    subtitle: "Image Gallery",
    desktopThumbnail: "/thumbnails/remembrance-gallery.png",
    desktopAlt: "",
    mobileThumbnail: "",
    mobileAlt: "",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: uuidv4(), text: "next.js" },
      { id: uuidv4(), text: "cloudinary" },
      { id: uuidv4(), text: "typescript" },
      { id: uuidv4(), text: "tailwind" },
    ],
    description: "Hello World!",
    linkRepository:
      "https://github.com/AndreiSager/family-friends_image-gallery",
    linkLiveDemo: "https://remembrance-gallery.vercel.app",
    linkCaseStudy: "",
  },
];
