// Sample
// {
//   id: 0,
//   title: "",
//   subtitle: "",
//   description: "",
//   desktopThumbnail: "",
//   desktopAlt: "",
//   mobileThumbnail: "",
//   mobileAlt: "",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [{ id: 1, tag: "" }],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },

export const FeaturedProjectsData = [
  {
    id: 1,
    title: "Roadway Delivery (Landing Page)",
    subtitle: "Transport Service",
    description:
      "Roadway Delivery Service is a leading logistics company revolutionizing the industry with fast, reliable road transportation solutions. We specialize in secure, on-time deliveries for customers and businesses across local and regional destinations.",
    desktopThumbnail:
      "/projects-short/road-way-delivery__compressed-desktop.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "/projects-short/road-way-delivery__compressed-mobile.jpg",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: 1, tag: "Next.js" },
      { id: 2, tag: "Typescript" },
      { id: 3, tag: "Headless UI" },
      { id: 4, tag: "Next Auth" },
      { id: 5, tag: "Emailjs" },
      { id: 6, tag: "Tailwind" },
      { id: 7, tag: "CSS" },
      { id: 8, tag: "Sass" },
    ],
    linkRepository: "https://github.com/AndreiSager/road-way-delivery",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "/",
  },

  // {
  //   id: 0,
  //   title: "Lorebuilder",
  //   subtitle: "World Building",
  //   description:
  //     "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque vitae magni maxime expedita, ea facilis modi incidunt quisquam corrupti velit! Similique eaque voluptas repudiandae iste aperiam consequatur accusantium porro nihil.",
  //   desktopThumbnail: "",
  //   desktopAlt: "Lorebuilder On Desktop",
  //   mobileThumbnail: "",
  //   mobileAlt: "Lorebuilder On Mobile",
  //   platformDesktop: true,
  //   platformMobile: true,
  //   tags: [{ id: 1, tag: "Electron.js" }],
  //   linkRepository: "/",
  //   linkLiveDemo: "/",
  //   linkCaseStudy: "/",
  // },
  // {
  //   id: 1,
  //   title: "Samura",
  //   subtitle: "e-commerce shop",
  //   description:
  //     "An online shop that sells a lot of products. It also has a dashboard for the seller and the user. Sellers can effortlessly manage their inventory, track orders, and engage with customers, while users can easily track their purchases, manage their profiles, and explore personalized recommendations.",
  //   desktopThumbnail: "",
  //   desktopAlt: "Samura On Desktop",
  //   mobileThumbnail: "",
  //   mobileAlt: "Samura On Mobile",
  //   platformDesktop: true,
  //   platformMobile: true,
  //   tags: [
  //     { id: 1, tag: "Next.js" },
  //     { id: 2, tag: "Typescript" },
  //     { id: 3, tag: "Tailwind" },
  //     { id: 4, tag: "CSS" },
  //   ],
  //   linkRepository: "/",
  //   linkLiveDemo: "/",
  //   linkCaseStudy: "/",
  // },
  // {
  //   id: 2,
  //   title: "Bridge",
  //   subtitle: "Social Platform",
  //   description:
  //     "Bridge is an all-in-one communication app designed to seamlessly connect you with friends and loved ones. With Bridge, you can effortlessly send messages to users and join engaging voice chats fostering meaningful conversations. Elevate your interactions with face-to-face connections through high-quality video calls, making every conversation feel personal and authentic. Stay connected like never before with Bridge – where messaging, voice chats, and video calls come together in one intuitive platform.",
  //   desktopThumbnail: "/projects-short/bridge__compressed-desktop.jpg",
  //   desktopAlt: "RWD full page on desktop",
  //   mobileThumbnail: "/projects-short/bridge__compressed-mobile.jpg",
  //   mobileAlt: "RWD full page on mobile",
  //   platformDesktop: true,
  //   platformMobile: true,
  //   tags: [
  //     { id: 1, tag: "Next.js" },
  //     { id: 2, tag: "Typescript" },
  //     { id: 3, tag: "Tailwind" },
  //     { id: 4, tag: "CSS" },
  //   ],
  //   linkRepository: "/",
  //   linkLiveDemo: "/",
  //   linkCaseStudy: "/",
  // },
  // {
  //   id: 3,
  //   title: "Roadway Delivery (App)",
  //   subtitle: "Social Platform",
  //   description:
  //     "Bridge is an all-in-one communication app designed to seamlessly connect you with friends and loved ones. With Bridge, you can effortlessly send messages to users and join engaging voice chats fostering meaningful conversations. Elevate your interactions with face-to-face connections through high-quality video calls, making every conversation feel personal and authentic. Stay connected like never before with Bridge – where messaging, voice chats, and video calls come together in one intuitive platform.",
  //   desktopThumbnail: "",
  //   desktopAlt: "RWD full page on desktop",
  //   mobileThumbnail: "",
  //   mobileAlt: "RWD full page on mobile",
  //   platformDesktop: true,
  //   platformMobile: true,
  //   tags: [
  //     { id: 1, tag: "Next.js" },
  //     { id: 2, tag: "Typescript" },
  //     { id: 3, tag: "Tailwind" },
  //     { id: 4, tag: "CSS" },
  //   ],
  //   linkRepository: "/",
  //   linkLiveDemo: "/",
  //   linkCaseStudy: "/",
  // },
];
