// Sample
// {
//   id: 0,
//   title: "",
//   subtitle: "",
//   description: "",
//   desktopThumbnail: "",
//   desktopAlt: "",
//   mobileThumbnail: "",
//   mobileAlt: "",
//   platformDesktop: true,
//   platformMobile: true,
//   tags: [{ id: 1, tag: "" }],
//   linkRepository: "/",
//   linkLiveDemo: "/",
//   linkCaseStudy: "/",
// },

export const OtherProjectsData = [
  {
    id: 0,
    title: "Marked A.I.",
    subtitle: "Artificial Intelligence",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque vitae magni maxime expedita, ea facilis modi incidunt quisquam corrupti velit! Similique eaque voluptas repudiandae iste aperiam consequatur accusantium porro nihil.",
    desktopThumbnail:
      "/projects-short/road-way-delivery__compressed-desktop.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "/projects-short/road-way-delivery__compressed-mobile.jpg",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: 1, tag: "Next.js" },
      { id: 2, tag: "Typescript" },
      { id: 3, tag: "Tailwind" },
      { id: 4, tag: "CSS" },
    ],
    linkRepository: "/",
    linkLiveDemo: "/",
    linkCaseStudy: "/",
  },
  {
    id: 1,
    title: "Shoutcaster",
    subtitle: "Video Sharing",
    description:
      "Welcome to Shoutcaster, our dedicated podcast platform, the ultimate destination for immersive audio experiences. Discover a world of knowledge, stories, and insights as you explore a diverse array of podcasts on our platform. Whether you're into captivating storytelling, thought-provoking discussions, or expert interviews, our platform offers a curated selection to cater to every interest. Immerse yourself in a universe of sound, where ideas and narratives come to life, all in one convenient podcast-exclusive platform.",
    desktopThumbnail:
      "/projects-short/road-way-delivery__compressed-desktop.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "/projects-short/road-way-delivery__compressed-mobile.jpg",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: 1, tag: "Next.js" },
      { id: 2, tag: "Typescript" },
      { id: 3, tag: "Tailwind" },
      { id: 4, tag: "CSS" },
    ],
    linkRepository: "/",
    linkLiveDemo: "/",
    linkCaseStudy: "/",
  },
  {
    id: 2,
    title: "Roadway Delivery (Landing Page)",
    subtitle: "Transport Service",
    description:
      "Roadway Delivery Service is a leading logistics company revolutionizing the industry with fast, reliable road transportation solutions. We specialize in secure, on-time deliveries for customers and businesses across local and regional destinations.",
    desktopThumbnail:
      "/projects-short/road-way-delivery__compressed-desktop.jpg",
    desktopAlt: "RWD full page on desktop",
    mobileThumbnail: "/projects-short/road-way-delivery__compressed-mobile.jpg",
    mobileAlt: "RWD full page on mobile",
    platformDesktop: true,
    platformMobile: true,
    tags: [
      { id: 1, tag: "Next.js" },
      { id: 2, tag: "Typescript" },
      { id: 3, tag: "Headless UI" },
      { id: 4, tag: "Next Auth" },
      { id: 5, tag: "Emailjs" },
      { id: 6, tag: "Tailwind" },
      { id: 7, tag: "CSS" },
      { id: 8, tag: "Sass" },
    ],
    linkRepository: "https://github.com/LordBrim/andrei-portfolio",
    linkLiveDemo: "https://roadwaydelivery.vercel.app",
    linkCaseStudy: "/",
  },
];
